# Application name and core config
spring:
  application:
    name: voting

  # Local PostgreSQL datasource (override with env vars if needed)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres.rpfxdhkirihjqyihyhpw}
    password: ${SPRING_DATASOURCE_PASSWORD:Helohapy@111}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:}

server:
  port: 8080

